controllers:
  echo:
    strategy: RollingUpdate
    containers:
      app:
        image:
          repository: ghcr.io/mendhak/http-https-echo
          tag: 37
        env:
          HTTP_PORT: 8080
          LOG_WITHOUT_NEWLINE: true
          LOG_IGNORE_PATH: /healthz
          PROMETHEUS_ENABLED: true
        probes:
          liveness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /healthz
                port: 8080
              initialDelaySeconds: 0
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
          readiness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /healthz
                port: 8080
              initialDelaySeconds: 0
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL
        resources:
          requests:
            cpu: 10m
          limits:
            memory: 64Mi
defaultPodOptions:
  securityContext:
    runAsNonRoot: true
    runAsUser: 65534
    runAsGroup: 65534
service:
  app:
    controller: echo
    ports:
      http:
        port: 8080
serviceMonitor:
  app:
    serviceName: echo
    endpoints:
      - port: http
route:
  app:
    hostnames:
      - echo.k8s.vierra.host
    parentRefs:
      - name: external
        namespace: kube-system
        sectionName: https
    rules:
      - backendRefs:
          - identifier: app
            port: 8080
sops:
  age:
    - recipient: age1hltlzj2xll67pnr5mjzq2rd4kfnqfdzammf2jc5x7tl0l5ke63tsnma8wc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtUUFQOWxBdzhaYjRoaGI4
        MmtIa3JpRGRndHFqbnorZnIwcC9FZ1c2YlZRClJFTEV4S3l5d3JmQVVWTTlheUto
        ZHZCN2RYenlvaUNKN2ZZbmZDbUI5UU0KLS0tIHRvWlpadHlxRHl2TTdlRzN3UWhU
        Ui9OOG5uTHBkc0FJL3BhNWVPOWUrNk0Kwtn5+B2lqtSPme8iQGPt+4Sj8A2vPvc5
        9Wsb2Nw/DyXzzvhxmQbxmdUSsoZvE+LWNIL1OfPqEWcIW55bN5T3Pg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-28T05:26:58Z"
  mac: ENC[AES256_GCM,data:M+elfr38KZ+fr0jFkUEn0JiKgYUggkufD9SgnujulV8g/Sw+Fntmmy5rs+u1U+tm1Y35oGgy7Zgdnc0xn1hjSK8XUmxsDYZZ+9Zuuzm+JwZpSYkovI75LGQoqu8TqgLy9qZJd5muhSf1VU4N2ruOtjz95E0487VWmpfTFNAwLOY=,iv:B4/J187Dz/wadutGkvm22+GTkPCXsBwFDIoCORWkYsg=,tag:yAqb2oCVfQ1mwDRIpJo11A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
