fullnameOverride: cloudflare-dns
provider: cloudflare
env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare-dns-secret
        key: api-token
extraArgs:
  - --cloudflare-dns-records-per-page=1000
  - --cloudflare-proxied
  - --crd-source-apiversion=externaldns.k8s.io/v1alpha1
  - --crd-source-kind=DNSEndpoint
  - --gateway-name=external
triggerLoopOnEvent: true
policy: sync
sources:
  - crd
  - gateway-httproute
txtPrefix: k8s.
txtOwnerId: default
# domainFilters: [""]
domainFilters:
  - k8s.vierra.host
serviceMonitor:
  enabled: true
podAnnotations:
  secret.reloader.stakater.com/reload: cloudflare-dns-secret
sops:
  age:
    - recipient: age1hltlzj2xll67pnr5mjzq2rd4kfnqfdzammf2jc5x7tl0l5ke63tsnma8wc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBieW01TUhsbWYvcGhPSWk4
        QTVnbm0yLzkyYkZWQWtvWHBCWU5HRHhMYTFvCmNVUlN2ZGpQSkxZT3RlMHRRMnNk
        Y3h4cG9sdWQvSmR5YkFpUzJrT0ZpdGMKLS0tIHg2cjlYK09NYUpJN3BnWDBnbTlL
        aGxSeGw0VU5yWEtSYlozLytmcG5IbE0K6uvxeed+7ehKkBKSsRH2BOcEefIJknzs
        ERLHOzAPFxRTrXdfrpOl8ZHl8ikglaLEBX+mshrYcEibb4R+TS3HJw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-28T05:26:58Z"
  mac: ENC[AES256_GCM,data:lNdWT94YimPgPnJNMtrJFy0EZvv9kh/wflbjHrPhXjtXKBy5niZnyBpndWyiebcz47bhIFEypMSYX6GfTXM74rgzwZh78b+eTE523Aox38Snp4gN0zSGQx77Kg6Anr0puGsa4Z2Eb5XQHgWu4vE9zZKFAUVylgKZ8BEr4FjZagQ=,iv:sxn9dww2ev2ysfXIILxFGdveSQbQPlPGffxpp8pAGAs=,tag:t3RM1tmWMvrOr/HSqBu9mQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
