# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/cert-manager.io/clusterissuer_v1.json
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cert-manager-secret
              key: api-token
        selector:
          dnsZones:
            - k8s.vierra.host
sops:
  age:
    - recipient: age1hltlzj2xll67pnr5mjzq2rd4kfnqfdzammf2jc5x7tl0l5ke63tsnma8wc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwWlJRYzFLU1VNTWlDN3pV
        b05FdUNRS3lNUnN3dnBwaGN1eUEzdnB5c0VBCmdFbDdQTk1pbHJZMUJzQTNUN1FE
        UEp2N3BjSndhVS8wbTgycWRnLy9vWmcKLS0tIDhNWllyVmNzZGtwTnBXeGJzang2
        N1cwZWIyTDBkMzZRdWp6cEFyei8rVEkKtCpQSJatdu3AC6rINwHmk8muvanh9aCd
        x7BoKn9fgKTzE6gpV/oEFgloy1dYY81xwZVqH5sC9uiWExCUOqaTuw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-28T05:26:58Z"
  mac: ENC[AES256_GCM,data:pgkO1655qP9Ti7xCEbRbzEwCXoBshmBzejw3aAVQdpP72aSRKVMLQemKDi6p4ICU2eU5iL3ziaSaeFwmHnpUWBEi3xGy8s7qfBPB0/tIr5qZJ6hngk+rZUHzyNndxTz6DViLJkSd1dOIYZCeOqYV/NcU6hWutIDpiabTiyT9TLg=,iv:pEU1ZZ3xEoKhKy5ZIg7Ve1NyFfRKUgIHmGnJfhXICzw=,tag:M32nAaFTMsExl37FTgCnWA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
