# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/cert-manager.io/clusterissuer_v1.json
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: letsencrypt-production
spec:
    acme:
        server: https://acme-staging-v02.api.letsencrypt.org/directory
        # server: https://acme-v02.api.letsencrypt.org/directory
        privateKeySecretRef:
            name: letsencrypt-production
        solvers:
            - dns01:
                cloudflare:
                    apiTokenSecretRef:
                        name: cert-manager-secret
                        key: api-token
              selector:
                dnsZones:
                    - vierra.host
sops:
    age:
        - recipient: age1hltlzj2xll67pnr5mjzq2rd4kfnqfdzammf2jc5x7tl0l5ke63tsnma8wc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0ZVhVWGVFbUVTUFZWamhV
            RzlCT21UMk9FQm00S0FkWXhvRysyVGFOZ213ClNWdElCd3pzRFhvd3Bqa1F4K3hj
            QUQrb3JqUklxdHJPUkJZOVVqemNjTnMKLS0tIHUzOVR1Zll4M2pmVDJ4R242a3BR
            cDgxOHV0UldoWXU1MDMyR21HTzNLb2MKAtCE1h8YcX5FgBCaQg1uJUHYbFkyp0+m
            p200ZRQEQdJCv3y88OY8uW22WCug4ztEcqHA+1jBKdbJHZduiYR5dg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-27T19:55:56Z"
    mac: ENC[AES256_GCM,data:dk3pyKjMsY4N/e0kRrgLzWbgJvt/2hc+dhrjZu0FQ2sJHvoi6C4C0h/6AayJzzRmdDilRYk9xN8UAppkCVtuJAAzGg/OPJ4ZPtE3+Q6Dsmg2+uP3+VXQyajkt75n1Y28ihRvLVmracf0py+GKUwxRSHvg2PRXrR0BA1NKpt8Bqc=,iv:d2S22PkwJDTu+h9PzFTnddli5MCK5+WqA3vdKOTow5w=,tag:/yvawdiRrlt9PmUBYlrCsA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.10.2
