apiVersion: v1
kind: Secret
metadata:
  name: helm-secrets-private-keys
stringData:
  key.txt: ENC[AES256_GCM,data:Y/2NJHOYDvLLOxV+S1wxNFK7nU71FiN0RbgSTEpb/EcIBp4tUG0V2R6SDbcY95HyERLDn5nt6YwZbrO6WUqDZhLihJuJGiLag9jf,iv:4hsYvOXsS9n+a/D5JSEIiHtO7q41T7cKyOmd1/5g568=,tag:Vx7kienrr5HZdnswma9QpA==,type:str]
sops:
  age:
    - recipient: age1hltlzj2xll67pnr5mjzq2rd4kfnqfdzammf2jc5x7tl0l5ke63tsnma8wc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmRlFIUkQvN3dubkdvVXRa
        RmpSNDJxakY0SFovb0dWby92M1FUZkt6ZWxrCjZSSjQyUTdTQVgrY3FZVTVlaGFZ
        TGEyd3J2Q0RJdUdKL2tsY0ZqSzdHYzQKLS0tIGFucGRYYzJ4ZWcvZTI5RHFtRWF2
        N1lKT0s3SEJGYUJWSkgyM01pRTAzMEUKhfxMHG1tgNC8Lpxo1hrDQoh7P9NdRIwy
        QT4N8fe5KhciX4+4Q7fe962MrODfMl8LGjfXHYkj6lHIM8ko/4t+8w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-27T19:50:20Z"
  mac: ENC[AES256_GCM,data:0qXQEzUEwtVIZkqOfm+oq4IbTdGtfQNGQ37+ebzBuGeQbT2582zngtDpSTI8/alCC8u7TGeMugq46HbGt1GOqtaWQBhHNxF4Iibtx7Zin74HGbu2Z24ovE3N3bpdQLKsmIDD7b5mwMa4+XMCnMjCXdo/9x2giqLBgDpbMhxmzKE=,iv:VQjHHBYmBzQ9UdqoimPaNYQYKTlnSQJCVALC75Qcx5g=,tag:wYNHShmOFe/xbFNe9KTehg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
