apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:WqczmZoK12YvuqSwQYgX6kuV7XPs0cHEj36EcX61S69QJH7Bj/DcnQ==,iv:u0iaVK+CqSuCfXuItH1oC4GV5po4uw61hA8OrRT4VRQ=,tag:mQHZ0TD7a8HB63YN8Jtq2Q==,type:str]
sops:
  age:
    - recipient: age1hltlzj2xll67pnr5mjzq2rd4kfnqfdzammf2jc5x7tl0l5ke63tsnma8wc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0a05Pd0padjVObEtHMDE4
        MmJzZUdEYm04YVZXeEVGYzFOQlpSSGRnUVRrCmVMTmMrNnV3RC9Lem53SVdpYkd0
        a1B6UUVkcUEzeVA1S3RGSVQ4TGtmbjAKLS0tIG82cFRQWmlMQnBsbXpqRU9jdmE5
        RlIzMkFqU2FzSm9NL3dudWVsVk9BbTgK4iMOam8x/obPTYDEMmDbMMQQtSpPXJUd
        MXm2v5E5yJ1wNU8HgVuViXCc8LSeDhOxp9ln4v00zNUz54XzhQlAmQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-28T05:26:58Z"
  mac: ENC[AES256_GCM,data:6om3vOVxqg6ieDpn4TUmpd8aEfDfJK4H0AvorK3/FfGqB9SVvePmRJHj/+a68VMuwy7b703xWjFDoYUkg+/Pd2w5KuoFPYatnk7d29V5lSqzZWNcly82sTkpIuuB1OLQSCnElQXmmkY/i1gsaqQ/rjh8qWJ/Wt7lx9AXFR6ftMU=,iv:BZYV9gvzSfRQW3Hsujt5QIBLqhlDChxGYFqGdCrqH4I=,tag:PsHfZm5V5ex6Iw+3u6ddsQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
