apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:rZeihZUxdu9SmTS9sepNRyuduNMHlV4iobVtHW7LIqVHYOI0PY6J7A==,iv:28cGMLQLiXd0s3ZVKxWi3ZrhHyD4fa1seVefSY23KLw=,tag:qMQ2O4c9I5bKNNstcVrcGA==,type:str]
sops:
  age:
    - recipient: age1hltlzj2xll67pnr5mjzq2rd4kfnqfdzammf2jc5x7tl0l5ke63tsnma8wc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1V1BGcGcwNzRNMXdYeERJ
        cGpURWhzcmc3Si84ODNXaDZvWVk3ZU9GVmxBCjgyMXZCc25zcEUyWjNocEwwQ2lB
        SWl5bU16YUtvQ1o5SUJnaTRDblFiTWsKLS0tIEpxUlZjYUpWb1FaLytHWUhIZDMr
        SlNvMUJDVHZEUHFiVUxXUWEwVVNYRU0KaF3QmM44/b5Wj4J4nBYwfXLyhmhIAcCT
        KL5xloltcfnifygSD9Lnu2at80uOu8fOaV3jYwCPq44mZgJoIvzqbw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-27T19:50:20Z"
  mac: ENC[AES256_GCM,data:qqzJmwBB21go/C4lz5dWx2aHGXdxVXceDpmFJTNGGMWSoSVecDpKN4ioSbaejCDPBzmmCexAZECpOZ74uKfzVCMF7MYp1+y6eICWoQckrNpO96ejNdFAEHzHTttWIUZ/VwtcVz9oXAy0vnvRyTS9nEp/X6jsUQH3TRCpLm3zPNs=,iv:ZWeMcrNb/C5W1NXqsygNZhHFmS90BsInAah3vYvtJyA=,tag:oW4zh/0S57UOX3fDSCYZpg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
