# yaml-language-server: $schema=https://github.com/datreeio/CRDs-catalog/raw/refs/heads/main/gateway.networking.k8s.io/gateway_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: internal
  annotations:
    external-dns.alpha.kubernetes.io/target: internal.k8s.vierra.host
spec:
  gatewayClassName: cilium
  addresses:
    - type: IPAddress
      value: 10.10.130.92
  infrastructure:
    annotations:
      external-dns.alpha.kubernetes.io/hostname: internal.k8s.vierra.host
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      hostname: '*.k8s.vierra.host'
      allowedRoutes:
        namespaces:
          from: Same
    - name: https
      protocol: HTTPS
      port: 443
      hostname: '*.k8s.vierra.host'
      allowedRoutes:
        namespaces:
          from: All
      tls:
        certificateRefs:
          - kind: Secret
            name: k8s-vierra-host-production-tls
sops:
  age:
    - recipient: age1hltlzj2xll67pnr5mjzq2rd4kfnqfdzammf2jc5x7tl0l5ke63tsnma8wc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwcHZkaURFMFVkdEpER3dC
        bVBENmhHSkxWRUdFZTFzQ2lZUC94SmhVdmpVCktLLzFnWnVuNk5jQ2hFOUZOTWxs
        bExXQVRuem55dGxrWkJsQ0l0a2FhV2cKLS0tIFIrSUFSK0krb2RWaHZCSXpGUE1z
        N2NqTDc1czBkMFo2S1lRdXlFcFFrZ2cK0NB43EIGvQ285OSmGBnRlnFaxrWz3Nf1
        degr+6QyR8+X40eUM0durzci20jW/i8cQxpqMI7B5cdrSWoQ5x0AcQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-28T05:26:58Z"
  mac: ENC[AES256_GCM,data:p2GDQfWeUONDqiBenAYmz8dOARnHmU024kdMufnudve8ZRt57OccdncdG7HZTorZ8N1dLx1wClfI3AJRmo4HbPPOLnVaUwNnai1p+UWlKt7/Zeo3lKojH/DsapgMvkGzgggPsapfbWRBzadc/C+y6h5B3TYZTiQsEirv+fumxsI=,iv:mKCLaZgSol7Zld1lFJmecic94bIoMqsqLc3+8NifXPo=,tag:YB4SQCXz7w5OeqhjxeXA6w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
